Repository co-browser/browser-use-mcp-server, pull requests merged in 2025-04, with the labels that each got.

#33 32 feature improve ci
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/workflows/ci.yml
  .github/workflows/mega-linter.yaml
  .github/workflows/python-publish.yml
  .github/workflows/release.yaml
  .mega-linter.yml
  Dockerfile
  README.md
Labels: enhancement

#36 fix: enhance project configuration with dynamic versioning and update CI workflow for artifact handling
  .bandit.yml
  .flake8
  .github/workflows/ci.yml
  .github/workflows/python-publish.yml
  .pylintrc
  Dockerfile
  pyproject.toml
  pyrightconfig.json
  server/__init__.py
  server/server.py
  src/browser_use_mcp_server/__init__.py
  src/browser_use_mcp_server/cli.py
  src/browser_use_mcp_server/server.py
Labels: bug, enhancement

#39 chore: added discord to readme
  README.md
Labels: documentation
